#! /bin/ksh
# Script to make a tar file for external distribution.

stamp=`date +_%y%m`
ESTMP=/tmp
DISTDIR=`pwd`
while [ $# -gt 0 ]
do case $1 in
     -d) DISTDIR=$2 ; shift 2 ;;
      *) shift ;;
   esac
done

MANPATH=./man:$MANPATH
export MANPATH

echo 'Creating tar file of radiation code for external distribution.'

mkdir ${ESTMP}/socrates${stamp}

# Copy package files
cp -r sbin data docs examples idl python man src make ${ESTMP}/socrates${stamp}/
cp README COPYRIGHT.txt build_code ${ESTMP}/socrates${stamp}/

# Update _version.txt file
fcm info | grep '^URL' > ${ESTMP}/socrates${stamp}/_version.txt
fcm info | grep "Last Changed Rev" >> ${ESTMP}/socrates${stamp}/_version.txt
fcm info | grep "Last Changed Date" >> ${ESTMP}/socrates${stamp}/_version.txt

# Remove unwanted files
cd ${ESTMP}/socrates${stamp}/ && find . -name *~ -exec rm -f {} \;
cd ${ESTMP}/socrates${stamp}/ && find . -name \.svn -exec rm -rf {} \; 2> /dev/null

echo 'Building documentation pdfs.'
cd ${ESTMP}/socrates${stamp}/docs/techguide
. ${ESTMP}/socrates${stamp}/docs/techguide/lx > /dev/null
mv socrates_techguide.pdf ../.
cd ..
rm -rf techguide
cd ${ESTMP}/socrates${stamp}/docs/userguide
. ${ESTMP}/socrates${stamp}/docs/userguide/lx > /dev/null
mv socrates_userguide.pdf ../.
cd ..
rm -rf userguide

echo 'Packaging distribution...'
cd ${ESTMP}
tar cJf socrates${stamp}.tar.xz socrates${stamp}/
mv ${ESTMP}/socrates${stamp}.tar.xz ${DISTDIR}/.
echo "Created file ${DISTDIR}/socrates${stamp}.tar.xz"

# Remove tmp directory
rm -rf ${ESTMP}/socrates${stamp} 2> /dev/null

exit 0
