name: Compile SOCRATES

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    name: Install and build
    steps:
      - uses: actions/checkout@v4

      - name: NetCDF
        run: |
          sudo apt update 
          sudo apt-get install libnetcdff-dev netcdf-bin gfortran gcc

      - name: Build
        run: |
          export LD_LIBRARY_PATH=""
          ./configure
          ./build_code 
          source set_rad_env 
          
      - name: Zip
        run: |
          zip -r socrates-${{ runner.os }} .

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: socrates-${{ runner.os }}.zip
          path: socrates-${{ runner.os }}.zip

      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     files: socrates-${{ runner.os }}.zip
